# Generated by Django 3.2.14 on 2023-05-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='number_of_posts',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
