# Generated by Django 3.2.14 on 2023-05-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_instauser_number_of_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='email address'),
        ),
    ]
