# Generated by Django 3.2.14 on 2023-05-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_instauser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='intagram_images'),
        ),
        migrations.AddField(
            model_name='instauser',
            name='password',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
