# Generated by Django 3.2.14 on 2023-05-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20230515_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
