# Generated by Django 3.2.14 on 2023-03-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(blank=True, max_length=2000, null=True)),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('email', models.EmailField(blank=True, max_length=2000, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('message', models.FileField(upload_to='template_images')),
            ],
        ),
        migrations.DeleteModel(
            name='Templates',
        ),
    ]
