# Generated by Django 3.2.14 on 2023-03-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0002_auto_20230310_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='API_key',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
